version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotchat_network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hotchat_network

volumes:
  mongodb_data:

networks:
  hotchat_network:
    driver: bridge
